### PR TITLE
CorGit submission for ETH Lisbon 2022 Hackathon

### PR DESCRIPTION
**Pull request by 70nyIT**

### CODE REVIEW

**Comment by 70nyIT** [comment]
hi @uF4No ! Any reason this is the only pull request not merged? Just wanted to make sure everything is fine on our side!

**Comment by uF4No** [comment]
Hi @70nyIT It's not merged cause it deletes the ZKSync Patron project, can you fix that?
In any case, even though it's not merged yet, I've included all the details of your project in our list of submissions that we're currently reviewing.

**Comment by 70nyIT** [comment]
thanks for the answer @uF4No ! My bad, thought I had to re-name that folder. Going to fix it!

**Comment by 70nyIT** [comment]
Should be fixed now @uF4No

**Review by uF4No — APPROVED** [review]
approved

**Pull request merged**
